- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - ironic-dsvm-standalone
        - ironic-tempest-dsvm-functional-python2
        - ironic-tempest-dsvm-functional-python3
        - ironic-grenade-dsvm
        - ironic-grenade-dsvm-multinode-multitenant
        - ironic-tempest-dsvm-ipa-partition-pxe_ipmitool-tinyipa-python3
        - ironic-tempest-dsvm-ipa-partition-redfish-tinyipa
        - ironic-tempest-dsvm-ipa-partition-uefi-pxe_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-wholedisk-agent_ipmitool-tinyipa-multinode
        - ironic-tempest-dsvm-ipa-wholedisk-bios-agent_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-wholedisk-bios-agent_ipmitool-tinyipa-indirect
        - ironic-tempest-dsvm-ipa-partition-bios-agent_ipmitool-tinyipa-indirect
        - ironic-tempest-dsvm-bfv
        # Non-voting jobs
        - ironic-tempest-dsvm-ipa-wholedisk-bios-pxe_snmp-tinyipa:
            voting: false
        - ironic-tempest-dsvm-ironic-inspector:
            voting: false
        - ironic-tempest-dsvm-pxe_ipmitool-postgres:
            voting: false
    gate:
      queue: ironic
      jobs:
        - ironic-dsvm-standalone
        - ironic-tempest-dsvm-functional-python2
        - ironic-tempest-dsvm-functional-python3
        - ironic-grenade-dsvm
        - ironic-grenade-dsvm-multinode-multitenant
        - ironic-tempest-dsvm-ipa-partition-pxe_ipmitool-tinyipa-python3
        - ironic-tempest-dsvm-ipa-partition-redfish-tinyipa
        - ironic-tempest-dsvm-ipa-partition-uefi-pxe_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-wholedisk-agent_ipmitool-tinyipa-multinode
        - ironic-tempest-dsvm-ipa-wholedisk-bios-agent_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-wholedisk-bios-agent_ipmitool-tinyipa-indirect
        - ironic-tempest-dsvm-ipa-partition-bios-agent_ipmitool-tinyipa-indirect
        - ironic-tempest-dsvm-bfv
