- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-victoria-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - ironic-tox-unit-with-driver-libs
        - ironic-standalone
        - ironic-standalone-redfish
        - ironic-tempest-functional-python3
        - ironic-tempest-partition-bios-redfish-pxe
        - ironic-tempest-partition-uefi-redfish-vmedia
        - ironic-tempest-wholedisk-bios-snmp-pxe
        - ironic-tempest-ipa-partition-pxe_ipmitool
        - ironic-tempest-ipa-partition-uefi-pxe_ipmitool
        - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode
        - ironic-tempest-bios-ipmi-direct-tinyipa
        - ironic-tempest-bfv
        - ironic-tempest-ipa-partition-uefi-pxe-grub2
        - metalsmith-integration-glance-localboot-centos7
        # Non-voting jobs
        - ironic-tox-bandit:
            voting: false
        - ironic-inspector-tempest:
            voting: false
        - ironic-inspector-tempest-managed-non-standalone:
            voting: false
        - ironic-inspector-tempest-partition-bios-redfish-vmedia:
            voting: false
        - ironic-tempest-ipa-wholedisk-bios-ipmi-direct-dib:
            voting: false
        - bifrost-integration-tinyipa-ubuntu-bionic:
            voting: false
        - ironic-tempest-pxe_ipmitool-postgres:
            voting: false
    gate:
      queue: ironic
      jobs:
        - ironic-tox-unit-with-driver-libs
        - ironic-standalone
        - ironic-standalone-redfish
        - ironic-tempest-functional-python3
        - ironic-tempest-partition-bios-redfish-pxe
        - ironic-tempest-partition-uefi-redfish-vmedia
        - ironic-tempest-wholedisk-bios-snmp-pxe
        - ironic-tempest-ipa-partition-pxe_ipmitool
        - ironic-tempest-ipa-partition-uefi-pxe_ipmitool
        - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode
        - ironic-tempest-bios-ipmi-direct-tinyipa
        - ironic-tempest-ipa-wholedisk-bios-agent_ipmitool-indirect
        - ironic-tempest-ipa-partition-bios-agent_ipmitool-indirect
        - ironic-tempest-bfv
        - ironic-tempest-ipa-partition-uefi-pxe-grub2
        - metalsmith-integration-glance-localboot-centos7
    experimental:
      jobs:
        # TODO(dtantsur): these jobs are useful but currently hopelessly
        # broken. Fix them and bring back to the gate.
        - ironic-tempest-ipxe-ipv6:
            voting: false
        - ironic-grenade-multinode-multitenant:
            voting: false
        - ironic-inspector-tempest-discovery-fast-track:
            voting: false
