---
- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-jobs
      - openstack-python3-jobs-arm64
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - ironic-tox-unit-mysql-migrations
        - ironic-tox-unit-with-driver-libs
        - ironic-cross-sushy:
            voting: false
        - ironic-tempest-functional-python3
        - ironic-standalone-redfish:
            voting: false
        - ironic-tempest-bios-redfish-pxe
        - ironic-tempest-uefi-redfish-vmedia
        - ironic-tempest-ramdisk-bios-snmp-pxe
        - ironic-tempest-uefi-redfish-https
        - ironic-tempest-ovn-uefi-ipmi-pxe
        - ironic-tempest-ovn-uefi-ipxe-ipv6
        - ironic-tempest-bios-ipmi-direct-tinyipa
        - ironic-tempest-bfv
        - ironic-tempest-ipa-partition-uefi-pxe-grub2
        - ironic-tempest-uefi-redfish-vmedia-4k
    gate:
      jobs:
        - ironic-tox-unit-mysql-migrations
        - ironic-tox-unit-with-driver-libs
        - ironic-tempest-functional-python3
        - ironic-tempest-bios-redfish-pxe
        - ironic-tempest-uefi-redfish-vmedia
        - ironic-tempest-ramdisk-bios-snmp-pxe
        - ironic-tempest-uefi-redfish-https
        - ironic-tempest-ovn-uefi-ipmi-pxe
        - ironic-tempest-ovn-uefi-ipxe-ipv6
        - ironic-tempest-bios-ipmi-direct-tinyipa
        - ironic-tempest-bfv
        - ironic-tempest-ipa-partition-uefi-pxe-grub2
        - ironic-tempest-uefi-redfish-vmedia-4k
