---
- name: BMO Functional Tests - Preparation
  hosts: all
  vars:
    bmo_source: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/metal3-io/baremetal-operator'].src_dir }}"
    local_install_path: /usr/local
    junit2html_venv: "{{ ansible_user_dir }}/venv"
    logdir: "{{ ansible_user_dir }}/metal3-logs"
    # Values hardcoded in BMO tests configuration
    redfish_emulator_address: 192.168.222.1
    redfish_emulator_port: 8000
  environment:
    PATH: "{{ local_install_path }}/bin:{{ ansible_env.PATH }}"

  tasks:
    - name: Install packages
      package:
        name:
          - dnsmasq
          - docker-buildx
          - docker.io
          - gettext-base
          - libvirt-clients
          - libvirt-daemon-system
          - libvirt-dev
          - ovmf
          - pkg-config
          - python3-venv
          - qemu-system-x86
          - squashfs-tools
          - xorriso
        state: present
      become: yes

    - name: Activate docker
      service:
        name: docker
        state: started
      become: yes

    - name: Activate libvirtd
      service:
        name: libvirtd
        state: started
        enabled: yes
      become: yes

    - name: Allow the current user to use docker and libvirt
      user:
        name: "{{ ansible_user_id }}"
        groups: docker,libvirt
        append: yes
      become: yes

    - name: Reset connection to apply group changes
      meta: reset_connection

    # NOTE(dtantsur): global pip is deliberately broken in Ubuntu, use venv
    - name: Create a venv for junit2html
      command: python3 -m venv "{{ junit2html_venv }}"
      args:
        creates: "{{ junit2html_venv }}"

    - name: Install junit2html
      pip:
        name: junit2html
        executable: "{{ junit2html_venv }}/bin/pip"

    - name: Ensure log directory exists
      file:
        path: "{{ logdir }}"
        state: directory

    - name: Enable access to sushy-tools in iptables
      iptables:
        chain: INPUT
        protocol: tcp
        destination: "{{ redfish_emulator_address }}"
        destination_port: "{{ redfish_emulator_port }}"
        jump: ACCEPT
        action: insert
        rule_num: 1
      become: yes

    - name: Copy cached Cirros images
      synchronize:
        src: "/opt/cache/files/"
        dest: "{{ bmo_source }}/test/e2e/images/"
        rsync_opts:
          - '--include=cirros-*-disk.img'
          - '--exclude=*'
      delegate_to: "{{ inventory_hostname }}"
