# NOTE(pas-ha) this is to ensure that partition metadata that might be stored
# in the start or end of partition itself also becomes unusable
# and does not interfere with future partition scheme if new partitions
# happen to fall on the same boundaries where old partitions were.
# NOTE(pas-ha) loop_control works with Ansible >= 2.1
- include_tasks: wipe.yaml
  with_dict: "{{ ansible_devices }}"
  loop_control:
    loop_var: device

- name: wipe general partition table metadata
  become: yes
  command: sgdisk -Z /dev/{{ item.key }}
  with_dict: "{{ ansible_devices }}"
  when:
    - item.value.host
